### ISSUE TITLE
time on database not working at users table

### ISSUE THREAD

**Issue by timonation** [infinitydevelopment14/id_playtimereward#13]
script not working. time is ruinning but not count on display and not shown in database. all the time 0

**Comment by Insaneshane99** [comment]
I also have this issue 

the hour in my database never changes

**Comment by isgrandson** [comment]
Are you getting any errors?

**Comment by timonation** [comment]
no errors

**Comment by isgrandson** [comment]
Do you have onesync enabled?

**Comment by timonation** [comment]
yes infinity

**Comment by isgrandson** [comment]
Any errors?

**Comment by timonation** [comment]
![image](https://user-images.githubusercontent.com/35240334/170955186-838cee10-2b21-4033-9ced-f88232f89da2.png)

**Comment by isgrandson** [comment]
Huh sorry, are you using latest version?

**Comment by isgrandson** [comment]
We are working on it, update will be done asap.
