### ISSUE TITLE
No changes in DB - ESX - OneSync without Infinity

### ISSUE THREAD

**Issue by extraditadosrp** [infinitydevelopment14/id_playtimereward#15]
First of all, thank you very much for the idea, it seems excellent to me and I hope to be able to fully implement it on my server. However, I am having problems.

I have downloaded and used versions **1.1.2**, **1.1.3**, **1.1.5** and they all give me the same error, after a player completes the time playing the time column is not updated, and an error appears on the server console same as next:

`[script:id_playtimere] SCRIPT ERROR: @id_playtimereward/server/server.lua:17: attempt to perform arithmetic on a nil value (field '?')`

**NOTE:** It should be noted that I have not modified anything in the script, and as it says in the title I am using OneSync without infinity

**Comment by isgrandson** [comment]
We are working on it, update will be done asap.
