### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by shadowTW** [infinitydevelopment14/id_playtimereward#2]
![image](https://user-images.githubusercontent.com/64441627/167604518-96bd7b58-4254-402a-b6da-76604b835cd7.png)

**Comment by amgmacht** [comment]
change that in your server and client

server/
https://prnt.sc/4D8CrSw8HhdW (Bearbeitet)

client/
https://prnt.sc/q2ZnmEqVEEM0

**Comment by amgmacht** [comment]
> 

did you bring your oxmasql up to date?

**Comment by amgmacht** [comment]
https://github.com/overextended/oxmysql/releases

**Comment by amgmacht** [comment]
Yes, I use the last version and I'm already looking at how I can get rid of the error. so please be patient

**Comment by infinitydevelopment14** [comment]
It has been fixed.
