### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Insaneshane99** [infinitydevelopment14/id_playtimereward#8]
![image](https://user-images.githubusercontent.com/87678580/167971821-e85fdec1-47a4-4db0-a03f-ee78ff126b34.png)

**Comment by Insaneshane99** [comment]
This issue appears to be related to license , if the player logs in with steam in the background it causes this error to appear , can you make this not require the license ?

**Comment by Insaneshane99** [comment]
Im also getting the following error

[script:id_playtimere] SCRIPT ERROR: @id_playtimereward/server/server.lua:28: attempt to compare nil with number
[script:id_playtimere] > ref (@id_playtimereward/server/server.lua:28)
[script:id_playtimere] > Query.onResult (@oxmysql/dist/build.js:21715)
[script:id_playtimere] > <unknown> (@oxmysql/dist/build.js:11918)
[script:id_playtimere] > processTicksAndRejections (node:internal/process/task_queues:78)

**Comment by Insaneshane99** [comment]
Looked at the database and also found the hour is not changing

**Comment by infinitydevelopment14** [comment]
Try downloading latest release version again.
**Do not change any Citizen.Wait if you do not know what you are doing!**

**Comment by Insaneshane99** [comment]
[script:id_playtimere] SCRIPT ERROR: @id_playtimereward/server/server.lua:28: attempt to compare nil with number
[script:id_playtimere] > ref (@id_playtimereward/server/server.lua:28)
[script:id_playtimere] > Query.onResult (@oxmysql/dist/build.js:21715)
[script:id_playtimere] > <unknown> (@oxmysql/dist/build.js:11918)
[script:id_playtimere] > processTicksAndRejections (node:internal/process/task_queues:78)
[      script:oxmysql] Uncaught Error: Error in nested ref call.
[      script:oxmysql] citizen:/scripting/v8/main.js(85,12): 
[      script:oxmysql] citizen:/scripting/v8/main.js(23,12): __cfx_wrap_42487
[      script:oxmysql] citizen:/scripting/v8/main.js(29,16): 
[      script:oxmysql] citizen:/scripting/v8/main.js(81,11): 
[      script:oxmysql] @oxmysql/dist/build.js(21715,20): 
[      script:oxmysql] @oxmysql/dist/build.js(11918,20): 
[      script:oxmysql] node:internal/process/task_queues(78,11): processTicksAndRejections
[      script:oxmysql] 
[      script:oxmysql] Error: Error in nested ref call.

**Comment by infinitydevelopment14** [comment]
Download oxmysql release and not source code.

**Comment by Insaneshane99** [comment]
still getting an error about license 

[ script:connectqueue] QUEUE: insan[license:edb6ba57a78ce596a8f72a720ed123d8505a50f1] was placed 1/1 in queue
[ script:connectqueue] QUEUE: insan[license:edb6ba57a78ce596a8f72a720ed123d8505a50f1] is loading into the server
[ citizen-server-impl] server thread hitch warning: timer interval of 329 milliseconds
[script:id_playtimere] SCRIPT ERROR: @id_playtimereward/server/server.lua:40: attempt to index a nil value (local 'Player')
[script:id_playtimere] > TriggerCallback (@qb-core/server/functions.lua:207)
[script:id_playtimere] > handler (@qb-core/server/events.lua:110)
[      script:qb-core] SCRIPT ERROR: error object is not a string

**Comment by timonation** [comment]
same problem here with the hours in database not updatet after 59 minutes

**Comment by Insaneshane99** [comment]
My database is also not updating , no errors on server or console
